name: Build and Test

on:
  push:
      branches: 
        - feature/*

env:
    PROJECT_ID: class-demo-387715 # TODO: update Google Cloud project id
    SERVICE: p3-api # TODO: update Cloud Run service name
    REGION: australia-southeast2  # TODO: update Cloud Run service region

jobs:
    build_test:
        runs-on: ubuntu-latest 

        steps:
            -   name:  Checout code
                uses:   actions/checkout@v2
                                
            -   name: Set up Node.js
                uses: actions/setup-node@v2
                with: 
                    node-version: 18

            -   name: Install dependencies
                run: npm install

            -   name: Build
                run: npm run build

            -   name:  Run Tests
                run: npm run test
        
            -   name: Google Auth
                id: auth
                uses: 'google-github-actions/auth@v0'
                with:
                    credentials_json: '${{ secrets.P3_CREDENTIALS }}'                

            -   name: Deploy to Cloud Run
                id: deploy
                uses: google-github-actions/deploy-cloudrun@v0
                with:
                    service: ${{ env.SERVICE }}
                    region: ${{ env.REGION }}
                # NOTE: If required, update to the appropriate source folder
                    source: ./                    

            -   name: Show Output
                run: echo ${{ steps.deploy.outputs.url }}                    